### ISSUE TITLE
Update for HumHub 1.0.1 and/or HumHub 1.1.0-beta.1 ?

### ISSUE THREAD

**Issue by tc-git-1** [benmag/humhub-modules-extend_search#2]
Are you available to update this module for use with HumHub 1.0.1 and/or HumHub 1.1.0-beta.1 ?

**Comment by benmag** [comment]
HumHub 1.0+ seems to have functionality that this module once offered.

**Comment by tc-git-1** [comment]
Any interest in working on a field specific user search Module for HumHub?
